In [9]:
import pandas as pd

s = pd.Series([1,2,3], index = ["First","Second","Third"])
print(f"The item index 1 is {s.iloc[1]}")
print(f"The item with the label Third is {s['Third']}")

The item index 1 is 2
The item with the label Third is 3

In [13]:
d = pd.DataFrame([1,2,3], [4,5,6])
d.index = ['a','b','c']
d

d = pd.DataFrame([[1,2,3],[4,5,6]], 
                index = ['a','b'],
                columns = ['One','Two','Three'])

d

   One  Two  Three
a    1    2      3
b    4    5      6

In [ ]:
#data = pd.read_csv('team.csv')
#data.head()
#data.tail()
#data.describe()
#data.columns
#data.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#data['Number of Socks']
#data.Age

#data[0:2]

#data.loc[0:3, ["Number of Socks", "Occupation"]]

,Name,Age,Occupation,Favorite Color,Number of Socks,Owns a Unicorn
0,Bartholomew,27,Cloud Architect,Electric Lime,17,False
1,Celeste,32,Professional Tea Taster,Mango,12,True

In [32]:
#data
#data[0:3]
#data.Age
#data['Number of Socks'].mean()

In [ ]:
data = pd.read_csv('melb_data.csv')
#data.columns
#round(data['Rooms'].mean())
#round(data['Price'].mean())

1075684

In [65]:
data['BuildingArea']
data = data.dropna(axis = 0)
data['BuildingArea']

1         79.00
2        150.00
4        142.00
6        210.00
7        107.00
          ...
12205    149.00
12206    115.00
12207     35.64
12209     61.60
12212    388.50
Name: BuildingArea, Length: 6196, dtype: float64

In [ ]:
from sklearn.tree import DecisionTreeRegressor

y = data.Price
features = ['Rooms', 'Bathroom','Landsize', 'Lattitude','Longtitude']
x = data[features]

melbourne_model = DecisionTreeRegressor(random_state = 1)

melbourne_model.fit(x,y)
print(f"Making predictions for the next five houses: ")
x.head()
print("The predictions are")
print(melbourne_model.predict(x.head()))
y.head()

ModuleNotFoundError: No module named 'sklearn'

In [2]:
import sys
print(sys.executable)

c:\Users\isaac\OneDrive\A-level Computer Science\.venv\Scripts\python.exe